### ISSUE TITLE
About the extracted feature

### ISSUE THREAD

**Issue by pengjinqiang** [GowthamGottimukkala/I3D_Feature_Extraction_resnet#1]
Thanks for your excellent work. I wonder that I3D has RGB and Flow pathway but it seems that you only user RGB image to extract I3D feature. So, if I use your code, I can only get RGB feature of I3D? Am I right?

**Comment by borijang** [comment]
Yes, that's right. This repo was made for [this method](https://arxiv.org/pdf/2101.10030.pdf), which only needs the I3D-RGB features.
