### ISSUE TITLE
ModuleNotFoundError: No module named 'models'

### ISSUE THREAD

**Issue by Nandini2801** [GowthamGottimukkala/I3D_Feature_Extraction_resnet#3]
Hi,
Nice work on feature extraction
I am facing a issue while running the below line of code:
python -m utils.convert_weights pretrained/i3d_baseline_32x2_IN_pretrain_400k.pkl pretrained/i3d_r50_kinetics.pth
It is giving out error: ModuleNotFoundError: No module named 'models'
I followed the following lines of code
! git clone https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet.git
!wget https://dl.fbaipublicfiles.com/video-nonlocal/i3d_baseline_32x2_IN_pretrain_400k.pkl -P pretrained/
cd I3D_Feature_Extraction_resnet
!python -m utils.convert_weights pretrained/i3d_baseline_32x2_IN_pretrain_400k.pkl pretrained/i3d_r50_kinetics.pth
can you help me with this issue?

**Comment by ro1406** [comment]
Hi @Nandini2801  I am currently having the same issue. Could you kindly guide me on how to solve it? Much appreciated :)

**Comment by xiuyangshengxi** [comment]
how to fix that problem?

**Comment by ro1406** [comment]
@xiuyangshengxi I had the same issue. I fixed it by simply putting the resnet.py file inside the utils folder (same directory as convert_weights.py) and changed line 59 in convert_weights.py to "from . import resnet". Good luck!

**Comment by Santosh-16k** [comment]
Copy the models folder from [pytorch-resnet3d](https://github.com/Tushar-N/pytorch-resnet3d) and place it inside the root folder. That should solve this issue.

**Comment by Run542968** [comment]
I fix this by changing the code in line 59. Specifically, "from models import resnet" -> "import resnet", this work.
