### ISSUE TITLE
I3D feature numpy file of dimension

### ISSUE THREAD

**Issue by xinghaizhu** [GowthamGottimukkala/I3D_Feature_Extraction_resnet#6]
for each video, why it saves I3D feature numpy file of dimension n/16 * 10 * 2048 where n is the no.of frames in the video?

**Comment by divypandya** [comment]
Hi @xinghaizhu 
As far as I understand this, n/16 is the total number of clips (divide video into clips of size 16 frames), for each clip you do 10 crop augmentation, and for each crop of a clip, you extract i3d features of shape 2048. Thus output tensor shape is [n/16, 10, 2048]
