### ISSUE TITLE
What's the meaning of the dimension respectively

### ISSUE THREAD

**Issue by yalimasinei** [GowthamGottimukkala/I3D_Feature_Extraction_resnet#9]
I use the sample video getting a .npy file which has the shape (170, 10, 2048)
Can you tell me the meaning of each dimension？
Thank you very much

**Comment by chamecall** [comment]
> I use the sample video getting a .npy file which has the shape (170, 10, 2048) Can you tell me the meaning of each dimension？ Thank you very much

- the  first dim is (num of frames in your video / 16)
- the second is always 10 according to 10 crops;
- the last one is feature dimension equal to 2048
